#apiVersion: v1
#kind: Secret
#metadata:
  #name: espresso-secret
#type: Opaque
#data:
  #username: dGVzdHVzZXI=
  #password: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-product-deployment
spec:
  #serviceName: "shop-web-service"
  replicas: 3
  selector:
    matchLabels:
      app: shop-product
  template:
    metadata:
      labels:
        app: shop-product
        version: v1
    spec:
      containers:
      - name: shop-product
        image: thimone/s7thimone:espressoproduct-v1.0.0
        ports:
        - containerPort: 80
  #volumeClaimTemplates:
  #- metadata:
     # name: shop-product-persistent-storage
    #spec:
    #  accessModes: [ "ReadWriteOnce" ]
     # resources:
      #  requests:
       #   storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-product-catalog-svc
spec:
  selector:
    app: shop-product
  ports:
    - protocol: TCP
      port: 8091  # Service port
      targetPort: 80  # Container port
  type: ClusterIP

