apiVersion: v1
kind: ConfigMap
metadata:
  name: espresso-reviews-configmap
data:
  SERVICE_VERSION: "v1"

---
#apiVersion: v1
#kind: Secret
#metadata:
  #name: espresso-reviews-secret
#type: Opaque
#data:
  #username: dGVzdHVzZXI=
  #password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: espresso-reviews-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espressoreviews1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop-reviews1
  template:
    metadata:
      labels:
        app: shop-reviews1
        version: v1
    spec:
      serviceAccountName: espresso-reviews-sa
      containers:
      - name: espressoreviews1
        image: thimone/s7thimone:espressoreviews-v1.0.0
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
              name: espresso-reviews-configmap

        #volumeMounts:
        #- name: secret-volume
          #mountPath: /etc/secret
      #volumes:
      #- name: secret-volume
        #secret:
          #secretName: espresso-reviews-secret

---
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
spec:
  selector:
    app: shop-reviews1
    #version: v2
  ports:
    - protocol: TCP
      port: 8092  # Service port
      targetPort: 80  # Container port
  type: ClusterIP

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: espressoreviews1-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: shop-reviews1

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: espressoreviews1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: espressoreviews1-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

