apiVersion: v1

kind: ConfigMap

metadata:

  name: espresso-reviews-configmap

data:

  app_config.yaml: |

    SERVICE_VERSION: "v1"



---

#apiVersion: v1

#kind: Secret

#metadata:

  #name: espresso-reviews-secret

#type: Opaque

#data:

  #username: dGVzdHVzZXI=

  #password: cGFzc3dvcmQ=



---

apiVersion: v1

kind: ServiceAccount

metadata:

  name: espresso-reviews-sa



---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: espressoreviews1-deployment

spec:

  replicas: 3

  selector:

    matchLabels:

      pap: espressoreviews1

  template:

    metadata:

      labels:

        pap: espressoreviews1

        version: v1

    spec:

      serviceAccountName: espresso-reviews-sa

      containers:

      - name: espressoreviews1

        image: thimone/s7thimone:espressoreviews-v1.0.0

        ports:

        - containerPort: 80

        env:

        - name: SERVICE_VERSION

          valueFrom:

            configMapKeyRef:

              name: espresso-reviews-configmap

              key: SERVICE_VERSION

        - name: POSTGRES_USER

          value: "postgres"

        - name: POSTGRES_PASSWORD

          value: "mysecretpassword"

        - name: POSTGRES_DB

          value: "mydatabase" 

        - name: POSTGRES_PORT

          value: "5432" 



        #volumeMounts:

        #- name: secret-volume

          #mountPath: /etc/secret

      #volumes:

      #- name: secret-volume

        #secret:

          #secretName: espresso-reviews-secret



---

apiVersion: v1

kind: Service

metadata:

  name: espresso-shop-reviews-svc

spec:

  selector:

    pap: espressoreviews1

  ports:

    - protocol: TCP

      port: 8092  # Service port

      targetPort: 80  # Container port

  type: ClusterIP



---

apiVersion: policy/v1

kind: PodDisruptionBudget

metadata:

  name: espressoreviews1-pdb

spec:

  minAvailable: 2

  selector:

    matchLabels:

      pap: espressoreviews1



---

apiVersion: autoscaling/v1

kind: HorizontalPodAutoscaler

metadata:

  name: espressoreviews1-hpa

spec:

  scaleTargetRef:

    apiVersion: apps/v1

    kind: Deployment

    name: espressoreviews1-deployment

  minReplicas: 2

  maxReplicas: 5

  targetCPUUtilizationPercentage: 80


