apiVersion: v1

kind: ConfigMap

metadata:

  name: espresso-configmap

data:

  lab_config.yaml: |

    ProductCatalogUrl: "http://espresso-shop-product-catalog-svc:8091"

    ReviewsUrl: "http://espresso-shop-reviews-svc:8092"

---

#apiVersion: v1

#kind: Secret

#metadata:

  #name: espresso-secret

#type: Opaque

#data:

  #username: dGVzdHVzZXI=

  #password: cGFzc3dvcmQ=



---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: shop-product-deployment

spec:

  #serviceName: "shop-web-service"

  replicas: 3

  selector:

    matchLabels:

      lab: shop-product



  template:

    metadata:

      labels:

        lab: shop-product



    spec:

      containers:

      - name: shop-product

        image: thimone/s7thimone:espressoproduct-v1.0.0

        ports:

        - containerPort: 80

        env:

        - name: ProductCatalogUrl

          valueFrom:

            configMapKeyRef:

              name: espresso-configmap

              key: ProductCatalogUrl

        - name: ReviewsUrl

          valueFrom:

            configMapKeyRef:

              name: espresso-configmap

              key: ReviewsUrl

        - name: POSTGRES_USER

          value: "postgres"

        - name: POSTGRES_PASSWORD

          value: "mysecretpassword"

        - name: POSTGRES_DB

          value: "mydatabase"

        - name: POSTGRES_PORT

          value: "5432" 



  #volumeClaimTemplates:

  #- metadata:

     # name: shop-product-persistent-storage

    #spec:

    #  accessModes: [ "ReadWriteOnce" ]

     # resources:

      #  requests:

       #   storage: 1Gi



---

apiVersion: v1

kind: Service

metadata:

  name: espresso-shop-product-catalog-svc

spec:

  selector:

    lab: shop-product

  ports:

    - protocol: TCP

      port: 8091  # Service port

      targetPort: 80  # Container port

  type: ClusterIP


