apiVersion: v1

kind: ConfigMap

metadata:

  name: espresso-reviews1-configmap

data:

  app_config.yaml: |

    SERVICE_VERSION: "v1"



---

apiVersion: v1

kind: ConfigMap

metadata:

  name: espresso-reviews2-configmap

data:

  app_config.yaml: |

    SERVICE_VERSION: "v2"



---

apiVersion: v1

kind: ConfigMap

metadata:

  name: espresso-configmap

data:

  app_config.yaml: |

    ProductCatalogUrl: "http://espresso-shop-product-catalog-svc:8091"

    ReviewsUrl: "http://espresso-shop-reviews-svc:8092"



---

#apiVersion: v1

#kind: Secret

#metadata:

#  name: espresso-secret

#type: Opaque

#data:

#  username: dGVzdHVzZXI=

#  password: cGFzc3dvcmQ=



---

apiVersion: v1

kind: ServiceAccount

metadata:

  name: shop-web-sa



---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: shop-web-deployment

spec:

  replicas: 3

  selector:

    matchLabels:

      app: shop-web

  strategy:

    type: RollingUpdate

    rollingUpdate:

      maxSurge: 1

      maxUnavailable: 1

  template:

    metadata:

      labels:

        app: shop-web

    spec:

      serviceAccountName: shop-web-sa

      containers:

      - name: shop-web

        image: thimone/s7thimone:espressoweb-v1.0.0

        ports:

        - containerPort: 80

        #livenessProbe:

        #  httpGet:

        #    path: /healthz

        #    port: 80

        #  initialDelaySeconds: 15

        #  periodSeconds: 10

        #readinessProbe:

        #  httpGet:

        #    path: /healthz

        #    port: 80

        #  initialDelaySeconds: 5

        #  periodSeconds: 5

        env:

        - name: ProductCatalogUrl

          valueFrom:

            configMapKeyRef:

              name: espresso-configmap

              key: ProductCatalogUrl

        - name: ReviewsUrl

          valueFrom:

            configMapKeyRef:

              name: espresso-configmap

              key: ReviewsUrl

        - name: SERVICE_VERSION1

          valueFrom:

            configMapKeyRef:

              name: espresso-reviews1-configmap

              key: SERVICE_VERSION

        - name: SERVICE_VERSION2

          valueFrom:

            configMapKeyRef:

              name: espresso-reviews2-configmap

              key: SERVICE_VERSION

        #volumeMounts:

        #- name: app-config-volume

        #  mountPath: /etc/espresso

        #- name: secret-volume

        #  mountPath: /etc/secret

      #volumes:

      #- name: app-config-volume

      #  configMap:

      #    name: espresso-configmap

      #- name: secret-volume

      #  secret:

      #    secretName: espresso-secret



---

apiVersion: v1

kind: Service

metadata:

  name: shop-web-service

spec:

  selector:

    app: shop-web

    lab: shop-product

    pap: espressoreviews1

  ports:

    - protocol: TCP

      port: 8090

      targetPort: 80

  type: NodePort



---

apiVersion: policy/v1

kind: PodDisruptionBudget

metadata:

  name: shop-web-pdb

spec:

  minAvailable: 2

  selector:

    matchLabels:

      app: shop-web



---

apiVersion: autoscaling/v1

kind: HorizontalPodAutoscaler

metadata:

  name: shop-web-hpa

spec:

  scaleTargetRef:

    apiVersion: apps/v1

    kind: Deployment

    name: shop-web-deployment

  minReplicas: 2

  maxReplicas: 5

  targetCPUUtilizationPercentage: 80


